#!/usr/bin/env python3

"""
Pack one or more 4-bit indexed grayscale PNGs (as produced by
python-projects/grayscale_image_conversion/prepare_image.py) into the
nibble-packed byte arrays Seeed_GFX expects for a GRAY_LEVEL16 EPaper sprite,
and emit them as PROGMEM C arrays in a single header for src/main.cpp to
include.

Packing format (confirmed against the vendored Seeed_GFX source under
.pio/libdeps/*/Seeed_GFX/, both in TFT_eSPI.cpp's 4bpp+cmap pushImage path
and TFT_eSprite::pushImage's _bpp==4 branch in Extensions/Sprite.cpp): each
byte holds two pixels, high nibble = first (even) pixel, low nibble = second
(odd) pixel. A 4bpp EPaper sprite stores the palette index directly as the
gray level (TFT_GRAY_0 = 0x00 = black ... TFT_GRAY_15 = 0x0F = white), which
is the same 0=black..15=white convention prepare_image.py's palette already
uses -- so no color-map translation is needed here.

All input images must share the same dimensions (the panel is a fixed
1872x1404, so this is normally already true if they came from
prepare_image.py's defaults).

Usage:
    python3 tools/convert_image.py ~/Pictures/test_1.png ~/Pictures/test_2.png
    python3 tools/convert_image.py --output src/image_data.h a.png b.png c.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


def pack_image(image: Image.Image) -> bytes:
    if image.mode != "P":
        raise ValueError(
            f"Expected a 4-bit palette ('P' mode) image, got mode {image.mode!r}. "
            "Run it through python-projects/grayscale_image_conversion/prepare_image.py "
            "first (--bit-depth 4)."
        )

    indices = list(image.getdata())

    if any(index > 15 for index in indices):
        raise ValueError(
            "Palette indices must fit in 4 bits (0-15) -- "
            "this doesn't look like a 4-bit grayscale image."
        )

    if len(indices) % 2 != 0:
        indices.append(0)

    packed = bytearray()
    for high, low in zip(indices[0::2], indices[1::2]):
        packed.append(((high & 0x0F) << 4) | (low & 0x0F))

    return bytes(packed)


def array_name(index: int) -> str:
    return f"IMAGE_DATA_{index + 1}"


def write_header(
    images: list[tuple[Path, bytes]],
    width: int,
    height: int,
    output_path: Path,
) -> None:
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/convert_image.py -- do not edit by hand.",
        f"// {width} x {height}, 4 bits per pixel, {len(images)} image(s).",
        "",
        f"constexpr int IMAGE_WIDTH = {width};",
        f"constexpr int IMAGE_HEIGHT = {height};",
        f"constexpr int IMAGE_COUNT = {len(images)};",
        "",
    ]

    for index, (source_path, packed) in enumerate(images):
        name = array_name(index)
        lines.append(f"// {name}: {source_path.name} ({len(packed)} bytes)")
        lines.append(f"const unsigned char {name}[] PROGMEM = {{")

        for offset in range(0, len(packed), 16):
            row = packed[offset : offset + 16]
            lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in row) + ",")

        lines.append("};")
        lines.append("")

    lines.append("const unsigned char *const IMAGES[IMAGE_COUNT] = {")
    for index in range(len(images)):
        lines.append(f"    {array_name(index)},")
    lines.append("};")
    lines.append("")

    output_path.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "inputs", type=Path, nargs="+", help="Source 4-bit indexed PNGs, in display order."
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("src/image_data.h"),
        help="Output header path (default: src/image_data.h).",
    )
    args = parser.parse_args()

    images: list[tuple[Path, bytes]] = []
    dimensions = None

    for input_path in args.inputs:
        resolved = input_path.expanduser()

        with Image.open(resolved) as image:
            if dimensions is None:
                dimensions = image.size
            elif image.size != dimensions:
                raise ValueError(
                    f"{resolved} is {image.size}, but {args.inputs[0].expanduser()} "
                    f"is {dimensions} -- all images must share the same dimensions."
                )

            images.append((resolved, pack_image(image)))

    width, height = dimensions

    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_header(images, width, height, args.output)

    total_bytes = sum(len(packed) for _, packed in images)
    print(
        f"Wrote {args.output} ({len(images)} image(s), {width}x{height}, "
        f"{total_bytes} bytes packed total)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
